{
  imports = [
    ./hostRoles/base.nix
    ./hostRoles/graphical.nix
    ./hostRoles/neural-augmenter.nix
    ./programs/firefox.nix
    ./programs/niri.nix
    ./programs/socials.nix
    ./programs/vscode.nix
    ./roles/art.nix
    ./roles/development.nix
    ./roles/gamedev.nix
    ./roles/gaming.nix
    ./roles/office.nix
    ./roles/vtubing.nix
    ./services/piper-web-tts.nix
    ./services/solaar.nix
  ];
}
